title: 'Geog 315 Advanced GIS'
description: 'Geog 315 T1 2022'
theme: jekyll-theme-minimal
site.baseurl: ''
site.url: 'https://dosull.github.io/Geog315'
author: "David O'Sullivan"
github_username: 'DOSull'
kramdown:
  auto_ids: true
