title: 'Geog 315'
description: 'Advanced GIS, VUW T2 2021'
theme: minima
site.baseurl: ''
site.url: 'https://dosull.github.io/Geog315'
header_pages:
  - index.md
  - logistics.md
  - schedule.md
  - lectures.md
  - videos.md
  - labs.md
  - assessments.md
  - clo.md
  - links.md
author: "David O'Sullivan"
github_username: 'DOSull'
