title: Geog 315 Course website
description: T2 2021
theme: minima
baseurl: ''
site.url: 'https://dosull.github.io/Geog315'
site.baseurl: ''
header_pages:
  - index.md
  - contacts.md
  - schedule.md
  - lectures.md
  - videos.md
  - labs.md
  - assessments.md
  - clo.md
  - links.md
